services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tgbot
      - NEXT_PUBLIC_SITEKEY=${NEXT_PUBLIC_SITEKEY}
      - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
      - ADMIN_ID=${ADMIN_ID}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tgbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: